# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
      args:
        ARG: -t
    image: hockeyallstar:latest
    volumes:
      - ./flask.log:/code/flask.log
    expose:
      - 6565
    ports:
      - 5000:6565
    environment:
      - COMET_API_KEY=${COMET_API_KEY}

  jupyter:
    build:
      context: ./
      dockerfile: ./Dockerfile.jupyter
      args:
        ARG: -t
    image: hockeyallstar_jupyter:latest
    expose:
      - 6566
    ports:
      - 5001:6566
